# GET  http://localhost:3001/api/notes

# GET  http://localhost:3001/api/notes/someInvalidId

# DELETE http://localhost:3001/api/notes/2

# POST http://localhost:3001/api/notes
# Content-Type: application/json

# {
#     "content": "lol",
#     "important": false
# }